language: node_js # specify your language
node_js: # specify options for your language
- '6.9'

# whitelist
branches:
  only:
    - master
    - /^deploy-.*$/ # regex ok

install:
  - npm install -g mocha
  - npm install
  
script:
  - cd es6
  - npm run babel
  - npm test
  
