apiVersion: v1
kind: Pod
metadata:
  name: mypod
  labels:
    purpose: demonstrate-command
spec:
  containers:
  - name: command-demo-container
    image: ubuntu
    command: ["printenv"]
    args: ["HOSTNAME", "KUBERNETES_PORT", "HOME"]
  - name: sleep-container
    image: ubuntu
    command: ["bash"]
    args: ["-c", "sleep", "600"]
  - name: nginx-container
    image: nginx
  restartPolicy: OnFailure
