apiVersion: v1
kind: Pod
metadata:
  name: testpod
  labels:
    purpose: "test-bash-sleep"
spec:
  containers:
  - name: sleep-container
    image: ubuntu
    command: ["bash"]
    args: ["-c 'sleep 60'"]
  restartPolicy: Never
